# Generated by Django 4.2 on 2023-05-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fooditems_audit_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodWaste',
            new_name='Food_Items',
        ),
    ]
