# Generated by Django 4.2.1 on 2023-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.TextField()),
                ('expiryDate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeID', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasteID', models.CharField(max_length=200)),
                ('itemID', models.CharField(max_length=200)),
                ('quantityWasted', models.TextField()),
                ('reason', models.TextField()),
                ('items', models.ManyToManyField(related_name='unused_field', to='app.fooditems')),
            ],
        ),
    ]
