# Generated by Django 4.2 on 2023-05-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='User',
        ),
    ]
