# Generated by Django 4.2 on 2023-05-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_recipe_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='Audit_Record',
        ),
    ]
