# Generated by Django 4.2 on 2023-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_foodwaste_food_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ingredients',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='recipeID',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instructions',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
